modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayTest="IGNORE_SERVER_VERSION"
description='''
ZstdNet is a Minecraft Java Edition mod that compresses relayed traffic between clients and servers through a local or server-side ZSTD proxy, with the goal of significantly reducing public bandwidth usage in high-repetition data scenarios.
It supports automatic dedicated-server port takeover, LAN host publishing, raw vanilla passthrough compatibility, and forwarded real-IP restoration.
'''

[features.${mod_id}]
javaVersion="[25,)"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[26.1,26.2)"
ordering="NONE"
side="BOTH"
